import app.routes.build_router
import app.routes.case_cooling_router
import app.routes.case_router
import app.routes.cpu_cooling_route
import app.routes.cpu_router
import app.routes.disk_enclosure_router
import app.routes.gpu_router
import app.routes.hdd_routes
import app.routes.motherboard_router
import app.routes.optical_drive_router
import app.routes.pci_controller_routes
import app.routes.psu_router
import app.routes.ram_router
import app.routes.sound_card_router
import app.routes.ssd_router
import app.routes.thermo_paste_router
