name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: [self-hosted, linux, X64]

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: m1xxos/amongpartsapi:latest
    
    - name: Brun docker image
      run: |
        docker rm -f api
        docker pull m1xxos/amongpartsapi
        docker run -d --name api -p 14888:80 -e MONGODB_URL='mongodb://root:example@13.49.227.110:27017' m1xxos/amongpartsapi

